### ISSUE TITLE
Issues when programmatically closing modals

### ISSUE THREAD

**Issue by soundsmitten** [jezuhke/js-modal#1]
When I call ``close()`` programmatically (for example, in an AJAX callback), I am unable to click on any form elements on the page when the modal disappears.

Workaround (quick-and-dirty): I made a function ``pClose()`` that applies 'visibility: hidden' to the modal and overlay. I make sure to toggle this class when the modal opens.

**Comment by jezuhke** [comment]
Sorry I never got to answer this. I'll have a look! Or else you can do a PR if you like!

**Comment by soundsmitten** [comment]
Turns out this really isn't an issue.

I have a fork. Added a toolbar reminiscent of Sencha syntax. It adds a bit of complexity to your work, though, so maybe we should keep it separate? If you want the code, it's my first PR ever, so bear with me :).
